# Why NumPy?

In [3]:
import numpy as np

### 1. With the help of the <i> np.array() </i>function, create a 1-D array variable <i> array_hw_1 </i> with the numbers from 1 to 8 and display it on the screen.

In [4]:
array_hw_1 = np.array([1,2,3,4,5,6,7,8])
array_hw_1

array([1, 2, 3, 4, 5, 6, 7, 8])

### 2.Check its type, shape and size. 
<i> (<b>Hint </b>: "type" is a Python function, while "shape" and "size" are attributes of the array) </i>

In [5]:
type(array_hw_1)

numpy.ndarray

In [7]:
array_hw_1.shape

(8,)

In [8]:
array_hw_1.size

8

### 3. Now, create a 2x4 2-D array, <i> array_hw_2</i> with the same values & display it on screen. 

In [9]:
array_hw_2 = np.array([[1,2,3,4],[5,6,7,8]])
array_hw_2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

### 4. Find its type, shape, and size. 

In [10]:
type(array_hw_2)

numpy.ndarray

In [11]:
array_hw_2.shape

(2, 4)

In [12]:
array_hw_2.size

8

### 5. Use square brackets to create a 3-D array with the same values as <i> array_hw_2 </i> and display it on screen.

In [16]:
array_hw_3 = np.array([[[1,2,3,4],[5,6,7,8]]])
array_hw_3

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]]])

### 6. Find its type, shape and size. 


In [17]:
type(array_hw_3)

numpy.ndarray

In [18]:
array_hw_3.shape

(1, 2, 4)

In [19]:
array_hw_3.size

8

### 7. Define a 2-D list <i> list_hw_1 </i> with the same values as <i> array_hw_2 </i>and display it on screen.

In [20]:
list_hw_1 = [[1,2,3,4],[5,6,7,8]]
list_hw_1

[[1, 2, 3, 4], [5, 6, 7, 8]]

### 8. Find the length of this 2-D list. 

In [21]:
len(list_hw_1)

2

### 9. Fint the length of one of its sublists. 

In [22]:
len(list_hw_1[0])

4

### 10. Verify its type. 

In [23]:
type(list_hw_1)

list

### 11. Use the <i>np.array()</i> function to create an array out of <i> list_hw_1</i> and display it on screen.

In [24]:
array_hw_4 = np.array(list_hw_1)

In [25]:
list_sum = list_hw_1[0] + list_hw_1[1]
list_sum

[1, 2, 3, 4, 5, 6, 7, 8]

### 12. Create two more variables and display them on screen:
    A) A list which is the sum of the two sublists of list_hw_1;
    B) An array which is the sum of the two subarrays of array_hw_4;
    
    (Hint: Use indexing to refer to the different sub-lists/arrays)

In [26]:
list_sum = list_hw_1[0] + list_hw_1[1]
list_sum

[1, 2, 3, 4, 5, 6, 7, 8]

In [27]:
array_sum = array_hw_4[0] + array_hw_4[1]
array_sum

array([ 6,  8, 10, 12])

### 13. Find the square roots of all the elements in <i> array_sum </i>
   <i> (<b>Hint</b>: Use the np.sqrt() function)

In [28]:
np.sqrt(array_sum)

array([2.44948974, 2.82842712, 3.16227766, 3.46410162])

### 13. Find the square roots of all the elements in <i> list_sum </i>
   <i> (<b>Hint</b>: Most NumPy functions are equipped to handle <b> lists </b>like ndarrays with the same shape)

In [29]:
np.sqrt(list_sum)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712])